[package]
name = "svanill"
description = "A command line tool to encrypt/decrypt your sensitive data."
version = "0.2.0"
authors = ["Riccardo Attilio Galli <riccardo@sideralis.org>"]
homepage = "https://svanill.com"
repository = "https://github.com/svanill/svanill-cli"
license = "AGPL-3.0-or-later"
readme = "README.md"
edition = "2018"

[dependencies]
structopt = "0.3.26"
ring = "0.16.20"
data-encoding = "2.4.0"
lazy_static = "1.4.0"
rpassword = "7.2.0"
nix = "0.26.2"
libc = "0.2.148"
thiserror = "1.0.50"
anyhow = "1.0.75"
atty = "0.2.14"
